### ISSUE TITLE
No matching method found: addPassword for class org.eclipse.aether.util.repository.AuthenticationBuilder

### ISSUE THREAD

**Issue by vemv** [cemerick/pomegranate#108]
Hi there,

I cannot release a library to Clojars. The last time I did was a few months ago so I may be making some silly mistake.

```
~/nrepl-debugger (master) $ lein with-profile +auth deploy clojars
Created /Users/victor.valenzuele/nrepl-debugger/target/nrepl-debugger-0.1.0-SNAPSHOT.jar
Wrote /Users/victor.valenzuele/nrepl-debugger/pom.xml
Error encountered performing task 'deploy' with profile(s): 'base,system,user,provided,dev,auth'
java.lang.IllegalArgumentException: No matching method found: addPassword for class org.eclipse.aether.util.repository.AuthenticationBuilder
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:80)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at cemerick.pomegranate.aether$authentication.invokeStatic(aether.clj:177)
	at cemerick.pomegranate.aether$authentication.invoke(aether.clj:173)
	at cemerick.pomegranate.aether$set_authentication.invokeStatic(aether.clj:184)
	at cemerick.pomegranate.aether$set_authentication.invoke(aether.clj:181)
	at cemerick.pomegranate.aether$make_repository.invokeStatic(aether.clj:207)
	at cemerick.pomegranate.aether$make_repository.invoke(aether.clj:200)
	at cemerick.pomegranate.aether$deploy_artifacts$fn__110.invoke(aether.clj:361)
```

This is how my :auth profile looks like:

```
:auth {:deploy-repositories [["releases" {:url "https://clojars.org/repo" :sign-releases false}]
                              ["snapshots" :clojars]]
        :repository-auth {#"https://clojars\.org/repo" {:username "vemv"
                                                        :password #=(some-> "CLOJARS_PASSWORD"
                                                                            System/getenv
                                                                            eval)}}}
```

What could be going on?

Thanks - Victor

**Comment by vemv** [comment]
The problem was in the `#=(some-> ` bit in my profile. I temporarily put my password as a string there and it worked.

Perhaps in Pomegranate you can `(assert (string? password))` for improving the error message :)
